config/routes.rb
Rails.application.routes.draw do
    devise_for :users
    
    resources :blogs
    root "blogs#index"
end

app/models/blog.rb
class Blog < ActiveRecord::Base
    belongs_to :user
    
    has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :blogs
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
    before_action :find_blog, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
    
    def index
    	@blogs = Blog.all.order("created_at DESC")
    end
    
    def show
    end
    
    def new
    	@blog = current_user.blogs.build
    end
    def create
    	@blog = current_user.blogs.build(blog_params)
    	
    	if @blog.save
    		redirect_to @blog, notice: "New post was created"
    	else
    		render "new"
    	end
    end
    
    def edit
    end
    
    def update
    	if @blog.update(blog_params)
    		redirect_to @blog, notice: "Post was succsessfully"
    	else
    		render "edit"
    	end
    end
    
    
    def destroy
    	@blog.destroy
    	redirect_to root_path
    end
    
    private
    	def blog_params
            params.require(:blog).permit(:image, :title, :body)
    	end
    	
    	def find_blog
    		@blog = Blog.find(params[:id])
    	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= form_for @blog do |f| %>

    <p class="form-group">
        <%= f.file_field :image, as: :file, class: "form-control", rows: "10", :required => 'required' %>
    </p>

    <p class="form-group">
        <%= f.label :title %><br>
        <%= f.text_field :title, class: "form-control", :required => 'required' %>
    </p>
    
    <pclass="form-group">
        <%= f.label :body %> <br>
        <%= f.text_area :body, class: "form-control", rows: "10", :required => 'required' %>
    </p>
    
    <p>
        <%= f.submit 'Blog it', :class => 'btn btn-info pull-right' %>
    </p>
<% end %>

app/views/blogs/edit.html.erb
<%= render 'form' %>

app/views/blogs/index.html.erb
<div class="wrapper_with_padding">
<% @blogs.each do |blog| %>
    <div class="box panel panel-default">
        <%= link_to(blog.title, blog) %><br>
        <span><%= truncate(blog.body, length: 150) %></span><br>
        <span><%= blog.user.email %></span>
    </div>
<% end %>
</div>

app/views/blogs/new.html.erb
<%= render 'form' %>

app/views/blogs/show.html.erb
<%= image_tag @blog.image.url(:medium) %>
<h1><%= @blog.title %></h1>
<p><%= @blog.body %></p>
<p><%= @blog.user.email %></p>

<% if user_signed_in? && current_user.id == @blog.user.id %>
    <%= link_to "Edit", edit_blog_path, class: "btn btn-info" %>
    <%= link_to "Delete", blog_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogIt</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<%= link_to "BLOGGER",  blogs_path, class: "navbar-brand"%>
			</div>
			<% if user_signed_in? %>
				<ul class="nav navbar-nav navbar-left">
					<li><%= link_to "Home",  blogs_path %></li>
					<li><%= link_to "Blog It!",  new_blog_path %></li>
				</ul>
			<% end %>
			<ul class="nav navbar-nav navbar-right">
				<% if user_signed_in? %>
				<li><%= link_to current_user.email, edit_user_registration_path %></li>
				<li><%= link_to("Log Out", destroy_user_session_path, method: :delete) %></li>
				<% else %>
				<li><%= link_to "Sign In", new_user_session_path %></li>
				<li><%= link_to "Register", new_user_registration_path %></li>
				<% end %>
			</ul>
		</div>
	</div>
	<div class="container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <%= yield %>
    </div>
    
  </body>
</html>